config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]
  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save

    redirect_to task_path(@task)
  end

  def edit; end

  def update
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/57d558e91d.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= simple_form_for(@task) do |f| %>
  <%= f.label :title %><br>
  <%= f.text_field :title, class: 'form-row' %><br>
  <%= f.label :details %><br>
  <%= f.text_field :details %><br>
  <% unless @task.new_record?%>
    <%= f.label :completed %>
    <%= f.check_box :completed %>
  <% end %>
  <%= f.button :submit, class: 'btn btn-primary btn-sm'%>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render "form", task: @task %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<p>
  <% @tasks.each do |task| %>
    <p>
      <% if task.completed %>
        <i class="far fa-check-square"></i>
      <% else %>
        <i class="far fa-square"></i>
      <% end %>
      <%= link_to task.title, task_path(task) %>
      <%= link_to task_path(task), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </p>
  <% end %>
</p>

<p>
  <%= link_to new_task_path do%>
    <i class="fas fa-plus">Add a new task</i>
  <% end %>
</p>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<h3><%= link_to 'Edit task', edit_task_path %></h3>

<p><%= @task.details %></p>
<p><input type="checkbox" <%= 'checked' if @task.completed %>> <%= @task.completed ? 'This task is completed' : 'This task is not completed yet' %></p>
<%= link_to 'Back to list', tasks_path %>